# Generated by Django 3.1.3 on 2022-07-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1', models.CharField(max_length=10)),
                ('v2', models.CharField(max_length=10)),
                ('v3', models.CharField(max_length=10)),
                ('v4', models.CharField(max_length=10)),
                ('v5', models.CharField(max_length=10)),
                ('v6', models.CharField(max_length=10)),
                ('v7', models.CharField(max_length=10)),
                ('v8', models.CharField(max_length=10)),
                ('v9', models.CharField(max_length=10)),
                ('v10', models.CharField(max_length=10)),
                ('v11', models.CharField(max_length=10)),
                ('v12', models.CharField(max_length=10)),
                ('v13', models.CharField(max_length=10)),
                ('v14', models.CharField(max_length=10)),
                ('v15', models.CharField(max_length=10)),
                ('v16', models.CharField(max_length=10)),
                ('v17', models.CharField(max_length=10)),
                ('res', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naive', models.FloatField(max_length=1000)),
                ('nn', models.FloatField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='graph2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naive', models.FloatField(max_length=1000)),
                ('nn', models.FloatField(max_length=1000)),
                ('svm', models.FloatField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='onlineuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
            ],
        ),
    ]
